server:
  port: 8002

spring:
  application:
    name: user-service8002
  datasource:
    url: jdbc:mysql://localhost:3306/db_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    hostname: user-service8002.com
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server7001.com:7001/eureka/,http://eureka-server7002.com:7002/eureka/
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.market.user.service8002.po.UserPo
