server:
  port: 8002

spring:
  application:
    name: user-service8002

eureka:
  instance:
    hostname: user-service8002.com
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server7001.com:7001/eureka/,http://eureka-server7002.com:7002/eureka/

